### ISSUE TITLE
OpenStack icon

### ISSUE THREAD

**Issue by bersace** [file-icons/DevOpicons#3]
Hi, Would you mind to have OpenStack logo in DevOpicons ? How to contribute ?

**Comment by Alhadis** [comment]
I should explain. The `file-icons` package contains multiple icon-fonts, only [one of which](https://github.com/file-icons/icons) receives active updates. The reason for this fragmentation is an unfortunate accident of history; before my involvement, the package was simply a [bundle of existing icon-fonts](https://github.com/file-icons/atom#icon-reference), one of which was Devicons. There was no centralised icon-font, meaning users had nowhere to submit new icons to. After I came along, I made an effort to merge as many icons into the same font as I possibly could. For compatibility reasons, however, the Devicons and Mfizz fonts had to remain separate.

I've added an OpenStack icon to the primary icon-font, which is simply named "file-icons" (it doesn't really have a name). I believe [`all-the-icons`](https://github.com/domtronn/all-the-icons.el#resource-fonts) includes it as part of its bundle, so you might see OpenStack's icon included there in a future update.

I hope this explanation wasn't too confusing. The `file-icons` project has a rather chaotic history.
