### ISSUE TITLE
Git icon details

### ISSUE THREAD

**Issue by bersace** [file-icons/DevOpicons#4]
Hi,

Here is a comparison between DevOpicon and [all-the-icon](https://github.com/domtronn/all-the-icons.el/blob/master/fonts/all-the-icons.ttf)

![image](https://user-images.githubusercontent.com/542613/73762993-21abb880-4771-11ea-8864-68352fe6cbfe.png)

DevOpicon is better sized and positionned, but all-the-icon is easier with commit node a bit larger. Especially when background and foreground colors are bright.

![image](https://user-images.githubusercontent.com/542613/73763467-b8787500-4771-11ea-979e-0e6b9e5a11f5.png)

What do you think of this ? Would it be possible to improve git icon ?

Thanks for DevOpicons.

**Comment by Alhadis** [comment]
I'm not sure what [`all-the-icons`](https://github.com/domtronn/all-the-icons.el#resource-fonts) is using for its Git icon, but it appears they've modified certain details of the [original/official icon](https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png) (whereas [ours](https://github.com/file-icons/DevOpicons/blob/64602d4cc92e4db729f22bedbbec6afeaefd3e56/svg/git.svg) matches the exact details of the original).

Modifying icon details to be clearer at tiny resolutions isn't something I'm averse to, but I *am* reluctant to modify icons that have been in-use for a long time. People get used to seeing the originals, and are sometimes bothered when noticeable changes are introduced without rhyme or reason. Hence why I try to avoid it when I can.

**Comment by bersace** [comment]
That's fair. Is DevOpicons popular enough to be as conservative ?

**Comment by Alhadis** [comment]
It's used in the [`file-icons`](https://atom.io/packages/file-icons) package for Atom, so yes, most certainly.
