### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by showmethecode9527** [file-icons/DevOpicons#5]
Please add a license file

**Comment by Alhadis** [comment]
From the [top of the readme](https://github.com/file-icons/DevOpicons#devopicons-optimised-devicons):

> This is simply a heavily-optimised version of the [Devicons](http://vorillaz.github.io/devicons/) font, created by [Theodore Vorillas](http://twitter.com/vorillas). All credit for the original icon vectors goes to him and his project's contributors; I've simply cleaned up the typeface by annihilating excess geometry, clearing duplicate control points, and basically just being a meticulous prick.

According to the original author's [`bower.json`](https://github.com/vorillaz/devicons/blob/ba75593fdf8d66496676a90cbf127d721f73e961/bower.json#L10) and [`package.json`](https://github.com/vorillaz/devicons/blob/ba75593fdf8d66496676a90cbf127d721f73e961/package.json#L20-L25) files, his work was released under the MIT license. However, there's no license file in his project's repository, nor do I feel impelled to write one on his behalf.

Does that answer your question?

**Comment by showmethecode9527** [comment]
Yeah, thanks.
